version: '3.9'

services:
  web:
    image: caddy:2.5.1-alpine
    container_name: money-backend-caddy-prod-container
    volumes:
      - .:/var/www/html/
      - ./docker/caddy:/etc/caddy/
    ports:
      - '8060:80'

  php:
    build: ./docker/php
    container_name: money-backend-php-prod-container
    volumes:
      - .:/var/www/html/