name: CICD

on: [push]

jobs:
  testing:
    name: Run PHP-CS-Fixer and PHPStan
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
        env:
          fail-fast: true

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit
        run: vendor/bin/php-cs-fixer fix --diff

      - name: Run PHPStan
        run: vendor/bin/phpstan

  deployment:
    name: Deploy the changes to my server
    runs-on: ubuntu-22.04
    needs: testing
    steps:
      - name: Run the deployment script
        uses: appleboy/ssh-action@master
        if: github.ref_name == 'master'
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: /bin/bash deployments/scripts/money-backend.sh